Repository Control-Cash/controlcash, pull requests merged in 2023-05, with the labels that each got.

#46 Docs/issue35
  docs/documento-de-modelos.md
Labels: documentation

#49 Divide requisitos funcionais "manter" em requisitos menores
  docs/documento-de-visao.md
Labels: documentation

#50 Atualiza requisitos envolvidos no caso de uso US01 #9
  docs/user-stories.md
Labels: documentation

#52 Corrige conexões do modelo de dados
  docs/documento-de-modelos.md
Labels: documentation

#54 Atualiza atividades feitas na iteração 1 #53
  docs/plano-iteracoes.md
Labels: documentation

#55 Doc/issue13
  docs/user-stories.md
Labels: documentation

#63 Visão geral do documento arquitetural #62
  docs/documento-arquitetural.md
  docs/img/django-architecture.png
Labels: documentação

#66 Implementando o User story base #19
  controlCash/settings.py
  controlCash/urls.py
  produto/__init__.py
  produto/admin.py
  produto/apps.py
  produto/migrations/0001_initial.py
  produto/migrations/__init__.py
  produto/models.py
  produto/templates/formCriarProduto.html
  produto/templates/formUpdateProduto.html
  produto/templates/home.html
  produto/templates/vizualizarProduto.html
  produto/tests.py
  produto/urls.py
  produto/views.py
Labels: aprimoramento

#65 Contagem de ponto de função do US01 - Manter Produto #56
  docs/documento-pontos-de-funcao.md
  docs/user-stories.md
Labels: documentação

#69 Doc/issue11
  docs/user-stories.md
Labels: documentação

#70 Doc: Fazendo contagem de pontos de função para o manter venda #58
  docs/documento-pontos-de-funcao.md
Labels: documentação

#67 Contagem de ponto de função do US02 - Manter Produto #57 - Docs/issue57
  docs/documento-pontos-de-funcao.md
Labels: documentação

#86 Fix/issue85 - Corrige testes do app venda
  .github/workflows/django.yml
  produto/signals.py
  requirements.txt
  venda/models.py
  venda/signals.py
  venda/tests/venda/test_models.py
  venda/tests/venda/views/test_item_views.py
  venda/tests/venda/views/test_venda_views.py
  venda/views/venda_views.py
Labels: bug, aprimoramento, Test
