Repository Control-Cash/controlcash, pull requests merged in 2023-06, with the labels that each got.

#89 Atualiza sonar-project.properties #88
  sonar-project.properties
Labels: aprimoramento

#91 Corrige erros nas views apontados pelo sonar
  produto/views.py
  venda/views/cliente_views.py
  venda/views/item_views.py
  venda/views/venda_views.py
Labels: aprimoramento

#93 Atualiza workflow django.yml
  .github/workflows/django.yml
Labels: aprimoramento

#92 Feat/issue78
  produto/templates/home.html
  produto/views.py
Labels: aprimoramento

#102 Descrever US08 - Manter cliente #98
  docs/documento-pontos-de-funcao.md
  docs/user-stories.md
Labels: documentação

#104 Adiciona descrição de US08 manter cliente #98
  docs/user-stories.md
Labels: documentação

#103 Formata instruções de execução do README #97
  README.md
Labels: documentação

#106 Descreve e implementa US13
  controlCash/settings.py
  controlCash/urls.py
  despesa/__init__.py
  despesa/admin.py
  despesa/apps.py
  despesa/forms.py
  despesa/migrations/0001_initial.py
  despesa/migrations/__init__.py
  despesa/models.py
  despesa/templates/despesa/criar.html
  despesa/templates/despesa/editar.html
  despesa/templates/despesa/listar.html
  despesa/templates/despesa/remover.html
  despesa/tests/__init__.py
  despesa/tests/despesa/__init__.py
  despesa/tests/despesa/test_models.py
  despesa/tests/despesa/test_views.py
  despesa/urls.py
  despesa/views.py
  docs/documento-pontos-de-funcao.md
  docs/user-stories.md
Labels: documentação, aprimoramento

#109 Configura uso da aplicação com o MariaDB
  .env.example
  .github/workflows/django.yml
  README.md
  controlCash/settings.py
  requirements.txt
Labels: aprimoramento

#112 Configura dockerimage e docker-compose
  .dockerignore
  .env.example
  Dockerfile
  controlCash/settings.py
  docker-compose.yml
Labels: aprimoramento
